version: 2.0
jobs:
  build:
    docker:
      - image: wholetale/girder:latest
      - image: mongo:3.4
    steps:
      - checkout
      - run:
          name: Installing Plugin Dependencies
          command: |
            apt-get update -qqy
            apt-get install -y sudo
            rm -rf /girder/plugins/virtual_resources
            cp -r /root/project /girder/plugins/virtual_resources
      - run:
          name: Install Test Dependencies
          environment:
            - LC_ALL: "C.UTF-8"
          command: |
            set -o pipefail; cd /girder ; python3 -m pip install -r requirements-dev.txt -e .[plugins,sftp] | cat
            set -o pipefail; cd /girder/pytest_girder ; python3 -m pip install . | cat
            cp /root/project/setup.cfg /girder/
            mkdir /girder/build
            chown -R girder:girder /girder
      - run:
          name: Running Tests
          environment:
            - PYTHON_VERSION: "3.9"
            - COVERAGE_EXECUTABLE: "/girder/venv/bin/coverage"
            - FLAKE8_EXECUTABLE: "/girder/venv/bin/flake8"
            - VIRTUALENV_EXECUTABLE: "/girder/venv/bin/virtualenv"
            - PYTHON_EXECUTABLE: "/girder/venv/bin/python3"
            - TEST_GROUP: "python"
            - HOME: "/home/girder"
          command: |
            sudo -E -u girder ctest -VV -S /girder/plugins/virtual_resources/cmake/circle_continuous.cmake
      - run:
          name: Install Codecov client
          command: python3 -m pip install codecov
      - run:
          name: Collect coverage reports
          command: coverage combine /girder/build/test/coverage/python_temp/
      - run:
          name: Uploading Coverage Results
          command: codecov
